# This is a configuration file for DEVELOPMENT which overrides
# `docker-compose.yml`

# See `docker-compose.yml` for more information.

version: "2"
services:
  web:
    restart: always

    # Expose the flask debug server port
    ports:
      - "5000:5000"

    # Let the application's Dockerfile speak for itself
    build: ./api

    # Expose our directories as volumes to the services.
    volumes:
      - ./api:/api
      - ./static:/static

    # Read configuration information from an environment file.
    env_file: ./env/env_file

    working_dir: /

    # Specific overrides that should be set regardless.
    environment:
      - FLASK_APP=api
      - FLASK_DEBUG=1
      - FLASK_ENV=development

    # Same as `docker-compose.yml`
    depends_on:
      - postgres
      - redis

    # Same as `docker-compose.yml`
    networks:
      - web_nw
      - db_nw

    # Don't bother with gunicorn. Use the flask debug server.
    command: flask run --host=0.0.0.0 --port 5000

  postgres:
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0

networks:
  web_nw:
    driver: bridge
  db_nw:
    driver: bridge
